### ISSUE TITLE
JSHint errors raised for JSX syntax on JS syntax errors.

### ISSUE THREAD

**Issue by clentfort** [STRML/JSXHint#45]
The following code causes jsxhint to early abort with an error on line 5 while the error is on line 8. (See the `var test test1;` statement.)

    var React = require('react');

    var t = React.createClass({
        render: function() {
            return <div>test</div>;
        },
    });
    var test test1;
    module.exports = t;

This is the error message.

    test.js: line 5, col 20, Expected an identifier and instead saw '<'.
    test.js: line 5, col 21, Missing semicolon.
    test.js: line 5, col 30, Unclosed regular expression.
    test.js: line 5, col 30, Unrecoverable syntax error. (50% scanned).

This makes it really hard to detect syntax errors that occur late in files.

**Comment by STRML** [comment]
Yeah, it appears that the syntax error is making it impossible to do the
compile, so jsxhint ends up linting the raw source.

Not much we can do about this.

The real solution is to switch to ESLint, which can actually lint the
source, rather than the compiled output.

I will be sunsetting this project soon.

**Comment by STRML** [comment]
I actually take this back; I sent that email late at night and didn't try out the problem myself.

I would suspect that something is actually wrong with your setup, or you are using a very old JSXHint version.

In #1, @caseywebdev submitted a patch for this very problem, which [is in our test suite](https://github.com/STRML/JSXHint/blob/master/test/test.js#L161).

This is the output I see from your example, which I put in `test_jsx_compile_error.jsx`:

```
~/g/o/J/t/fixtures (master|…) $ jsxhint test_jsx_compile_error.jsx
Error while transforming jsx in file test_jsx_compile_error.jsx
 Error: Parse Error: Line 8: Unexpected identifier
    at throwError (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2644:21)
    at throwUnexpected (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2688:13)
    at consumeSemicolon (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2829:13)
    at parseVariableStatement (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:4600:9)
    at parseStatement (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5402:24)
    at parseSourceElement (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6139:24)
    at parseProgramElement (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6185:16)
    at parseProgramElements (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6217:29)
    at parseProgram (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6230:16)
    at Object.parse (/usr/local/lib/node_modules/jsxhint/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:7566:23)
test_jsx_compile_error.jsx: line 8, col 10, Unexpected identifier

1 error
```

That is the expected error and SublimeLinter-jsxhint highlights it appropriately.

**Comment by clentfort** [comment]
Okay, I think I found where this problem is coming from: My files are named `.js` and do not have a pragma jsx in my files. If I renamed my file to `.jsx` they are linted properly.

According to 1387d20d7dbf7ec28e87bb93bce10016c6862752 all `.js` files should be transformed prior sending to JSHint.

**Comment by clentfort** [comment]
Ok, I figured what goes wrong. Since my files are not `.jsx` this check https://github.com/STRML/JSXHint/blob/master/jsxhint.js#L82 fails.

**Comment by STRML** [comment]
This is fixed in #62.

**Comment by minsooshin** [comment]
@STRML 

I am still getting same error on this. Could you let me know what is wrong on my setting?

javascript code
```js
var Comment = React.createClass({
  rawMarkup: function() {
    'use strict';

    var rawMarkup = marked(this.props.children.toString(), {sanitize: true});
    return { __html: rawMarkup };
  },

  render: function() {
    'use strict';

    return (
      <div className="comment">
        <h2 className="commentAuthor">
          { this.props.author }
        </h2>
        <span dangerouslySetInnerHTML={this.rawMarkup()} />
      </div>
    );
  }
});
```

console output
```sh
Running "jshint:all" (jshint) task

js/example.js
  line 3   col 5   Redefinition of 'Comment'.
  line 18  col 10  Unclosed regular expression.
  line 18  col 10  Unrecoverable syntax error. (12% scanned).

  ✖  2 errors
  ⚠  1 warnings

Warning: Task "jshint:all" failed.
```

package.json
```json
"grunt-jsxhint": "^0.6.0",
```

Gruntfile.js
```js
jshint: {
  options: {
    jshintrc: '.jshintrc',
    ignores: [],
    additionalSuffixes: ['.js'],
    reporter: require('jshint-stylish')
  },
  all: {
    src: ['js/**/*.js']
  }
},
```

**Comment by STRML** [comment]
You're running jshint, not jsxhint.

https://www.npmjs.com/package/grunt-jsxhint

But in any case, don't run JSXHint either. Use ESLint.
